name: portfolio_with_flutter
description: Ever seen an app transform with a button press? With Flutter's new 'Interactive Viewer', my portfolio app does just that! Tap a button, and the background color changes, a musical note plays, and you can even drag and zoom widgets. Cool, huh?

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  audioplayers:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - images/
    - assets/


  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf


    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
